# Copyright (c) 2026 SoftSiliconX Pvt Ltd
# All rights reserved.
#
# File Name        : ssxconfig.yaml
# File Description :
# Author           : Santhosh
# Date             : 2026-06-28

company: SoftSiliconX Pvt Ltd
author: Santhosh
year: 2026
use_gitignore: true
use_ssxignore: true
report: console
